---
- name: Configure zones for sig0namectl
  hosts: dns_servers
  vars:
    # allow_new_zones: true # allow zone management through rndc
    bind_zone_ttl: "30" # wind down cacheing TTL to 30 seconds
    bind_zone_subdirs: true
    bind_zones:
      - name: vmtest.zenr.io
        auto_dnssec: maintain
        create_reverse_zones: false
        primaries:
          - "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"
          - "{{ ansible_default_ipv6.address|default(ansible_all_ipv6_addresses[0]) }}"
        name_servers:
          - ns1.example.com.
          - ns2.example.com.
        update_policy_sig0:
          - "TODO: POLICY IS STILL HARDCODED IN TEMPLATE"
          - "grant \"vortex.zenr.io\" name zenr.io. ANY"
          - "grant \"vortex.zenr.io\" subdomain zenr.io. ANY"
          - "grant * selfsub . ANY"
        hosts:
          - name: '@'
            ip: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"
            ipv6: "{{ ansible_default_ipv6.address|default(ansible_all_ipv6_addresses[0]) }}"
      - name: _signal.vmtest.zenr.io
        auto_dnssec: maintain
        create_reverse_zones: false
        primaries:
          - "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"
          - "{{ ansible_default_ipv6.address|default(ansible_all_ipv6_addresses[0]) }}"
        check_names: warn
        name_servers:
          - ns1.example.com.
          - ns2.example.com.
        allow_update: ['any']
        hosts:
          - name: '@'
            ip: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"
            ipv6: "{{ ansible_default_ipv6.address|default(ansible_all_ipv6_addresses[0]) }}"
  roles:
    - bind9
