---
- name: Install some packages
  hosts: dns_servers
  vars:
    bind_zones:
      - name: vmtest.zenr.io
        create_reverse_zones: false
        primaries:
          - 192.168.122.212
        name_servers:
          - ns1.example.com.
          - ns2.example.com.
        hosts:
          - name: '@'
            ip: 127.1.0.1
  roles:
    - bind9
