---
- name: Configure zones for sig0namectl
  hosts: dns_servers
  vars:
    bind_zones:
      - name: vmtest.zenr.io
        create_reverse_zones: false
        primaries:
          - "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"
          - "{{ ansible_default_ipv6.address|default(ansible_all_ipv6_addresses[0]) }}"
        name_servers:
          - ns1.example.com.
          - ns2.example.com.
        hosts:
          - name: '@'
            ip: 127.1.0.1
      - name: _signal.vmtest.zenr.io
        create_reverse_zones: false
        primaries:
          - "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"
          - "{{ ansible_default_ipv6.address|default(ansible_all_ipv6_addresses[0]) }}"
        name_servers:
          - ns1.example.com.
          - ns2.example.com.
        allow_update: ['any']
        hosts:
          - name: '@'
            ip: 127.1.0.1
  roles:
    - bind9
