name: "test"

on: [push]

jobs:
  gotest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Run tests
        run: go test -v ./...
        working-directory: ./golang
      - name: Check WASM compilation
        run: GOOS=js GOARCH=wasm go build -o test.wasm
        working-directory: ./golang/wasm